### ISSUE TITLE
Can't interpolate more than one variable inside template string

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/i18n-yummy#1]
Seems that the `i18n-yummy` method only allows for passing in one variable into the template string. If I pass in more than one than it always replaces it with the value of the first one.

[Simple test](https://codepen.io/jaschaio/pen/ZjxQwz):

```
var one = 'First';
var two = 'Second';

console.log( i18n`i18n: ${ one } vs ${ two }` );
console.log( `normal: ${ one } vs ${ two }` );
```

Outputs:

```
i18n: First vs First
normal: First vs Second
```

instead of the expected output:

```
i18n: First vs Second
normal: First vs Second
```

**Comment by WebReflection** [comment]
```js
Object.defineProperty(
  Object.prototype,
  '::',
  {
    configurable: false,
    get: function () {
      var self = this;
      return function (callback) {
        return function () {
          return callback.apply(self, arguments);
        };
      };
    }
  }
);

const {map, sort} = Array.prototype;
document.querySelectorAll('*')
  ['::'](map)(el => el.nodeName)
  ['::'](sort)();
```
🍾💩🎉

jokes a part, I think why not having both ? it's good to have options for both functional and OO programmers, IMO.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/i18n-yummy#how-to

**Comment by WebReflection** [comment]
sorry for the wrong copy+paste ... so the link is the how to:

  * where is your database?
  * where is your locale?

If you don't have any of these you need to use [i18n-dummy](https://github.com/WebReflection/i18n-dummy) until you create one.

Then you need to the utility to create the db, then you need the DB, then it works.

Please read blogpost and documentation before filing bugs, thank you.
