### ISSUE TITLE
add documentation to the README file

### ISSUE THREAD

**Issue by kxrom** [WebReflection/i18n-yummy#2]
I'd ♥ to read further instructions for using your i18n tools!

I cannot find a out-of-the-box `Hello World` example, I keep having errors, with this line: `let db = i18n.db[locale] || (i18n.db[locale] = {});` or elsewhere.

How does a valid `i18n.db = {...}` database look like?

- https://github.com/WebReflection/i18n-yummy
- https://github.com/WebReflection/i18n-dummy
- https://github.com/WebReflection/i18n-utils

Thanks again! Great tool!

**Comment by WebReflection** [comment]
https://github.com/WebReflection/i18n-utils#quick-introduction
